title: Surya Narayanan Hari
description: PhD Student at Caltech researching brain algorithms
url: https://surya-narayanan.github.io

plugins:
  - jekyll-redirect-from

# Redirect settings
redirect_from:
  enabled: true

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal

baseurl: ""

#ins_logo: "./bits-logo.png"

# GoatCounter analytics. Dashboard: https://<code>.goatcounter.com  Leave blank to disable.
goatcounter: surya-narayanan

footer: no
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Contact"
    link: "contact"
  - name: "Resume"
    link: "resume.pdf"
# Force rebuild Wed Jul 30 11:30:00 PDT 2025 - CLEAN VERSION
