title: Surya Narayanan Hari
description: PhD Student at Caltech researching brain algorithms
url: https://surya-narayanan.github.io

plugins:
  - jekyll-redirect-from

# Redirect settings
redirect_from:
  enabled: true

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

baseurl: ""

#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Forked from design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Bento"
    link: "http://bento.me/ecstaticindian"
  - name: "Resume"
    link: "resume.pdf"
  # - name: "Personal"
  #   link: "personal"
  # - name: "Blog"
#    link: "blog"
# Force rebuild Wed Jul 30 00:12:20 PDT 2025
